export type ShiprocketCourierSeed = {
  id: number
  name: string
  businessType: Array<'b2c' | 'b2b'>
}

export const SHIPROCKET_COURIER_SEEDS: ShiprocketCourierSeed[] = [
  { id: 1, name: 'Blue Dart', businessType: ['b2c', 'b2b'] },
  { id: 4, name: 'Amazon Shipping 5Kg', businessType: ['b2c', 'b2b'] },
  { id: 6, name: 'DTDC Surface', businessType: ['b2c', 'b2b'] },
  { id: 10, name: 'Delhivery', businessType: ['b2c', 'b2b'] },
  { id: 14, name: 'Ecom Express Surface', businessType: ['b2c', 'b2b'] },
  { id: 18, name: 'DTDC 5kg', businessType: ['b2c', 'b2b'] },
  { id: 19, name: 'Ecom Express Surface 2kg', businessType: ['b2c', 'b2b'] },
  { id: 23, name: 'Xpressbees 1kg', businessType: ['b2c', 'b2b'] },
  { id: 24, name: 'Xpressbees 2kg', businessType: ['b2c', 'b2b'] },
  { id: 25, name: 'Xpressbees 5kg', businessType: ['b2c', 'b2b'] },
  { id: 29, name: 'Amazon Shipping 1Kg', businessType: ['b2c', 'b2b'] },
  { id: 32, name: 'Amazon Shipping 2Kg', businessType: ['b2c', 'b2b'] },
  { id: 33, name: 'Xpressbees', businessType: ['b2c', 'b2b'] },
  { id: 35, name: 'Aramex International', businessType: ['b2c', 'b2b'] },
  { id: 39, name: 'Delhivery Surface 5 Kgs', businessType: ['b2c', 'b2b'] },
  { id: 43, name: 'Delhivery Surface', businessType: ['b2c', 'b2b'] },
  { id: 45, name: 'Ecom Express Reverse', businessType: ['b2c', 'b2b'] },
  { id: 46, name: 'Shadowfax Reverse', businessType: ['b2c', 'b2b'] },
  { id: 48, name: 'Ekart Logistics', businessType: ['b2c', 'b2b'] },
  { id: 51, name: 'Xpressbees Surface', businessType: ['b2c', 'b2b'] },
  { id: 54, name: 'Ekart Logistics Surface', businessType: ['b2c', 'b2b'] },
  { id: 55, name: 'Blue Dart Surface', businessType: ['b2c', 'b2b'] },
  { id: 58, name: 'Shadowfax Surface', businessType: ['b2c', 'b2b'] },
  { id: 60, name: 'Ecom Premium and ROS', businessType: ['b2c', 'b2b'] },
  { id: 61, name: 'Delhivery Reverse', businessType: ['b2c', 'b2b'] },
  { id: 64, name: 'Delhivery 500G Savex (A)', businessType: ['b2c', 'b2b'] },
  { id: 65, name: 'Delhivery 500G Savex (S)', businessType: ['b2c', 'b2b'] },
  { id: 66, name: 'Ecom Exp Savex (A)', businessType: ['b2c', 'b2b'] },
  { id: 67, name: 'Ecom ROS Savex (A)', businessType: ['b2c', 'b2b'] },
  { id: 69, name: 'Kerry Indev Express Surface', businessType: ['b2c', 'b2b'] },
  { id: 71, name: 'Self Delivery', businessType: ['b2c', 'b2b'] },
  { id: 72, name: 'Bluedart Savex (A)', businessType: ['b2c', 'b2b'] },
  { id: 75, name: 'SRF Standard 500gm', businessType: ['b2c', 'b2b'] },
  { id: 76, name: 'Delhivery 5KG Savex (S)', businessType: ['b2c', 'b2b'] },
  { id: 77, name: 'Delhivery 10KG Savex (S)', businessType: ['b2c', 'b2b'] },
  { id: 78, name: 'Delhivery 20KG Savex (S)', businessType: ['b2c', 'b2b'] },
  { id: 79, name: 'SRF Standard 2kg', businessType: ['b2c', 'b2b'] },
  { id: 81, name: 'SRF Standard', businessType: ['b2c', 'b2b'] },
  { id: 82, name: 'DTDC 2kg', businessType: ['b2c', 'b2b'] },
  { id: 83, name: 'Delhivery 500G Savex RVP', businessType: ['b2c', 'b2b'] },
  { id: 84, name: 'Delhivery 500G Savex RVP-QC', businessType: ['b2c', 'b2b'] },
  { id: 85, name: 'Standard', businessType: ['b2c', 'b2b'] },
  { id: 86, name: 'Express', businessType: ['b2c', 'b2b'] },
  { id: 87, name: 'Delhivery 5KG Savex RVP (S)', businessType: ['b2c', 'b2b'] },
  { id: 88, name: 'Delhivery 10KG Savex RVP (S)', businessType: ['b2c', 'b2b'] },
  { id: 89, name: 'Delhivery 20KG Savex RVP (S)', businessType: ['b2c', 'b2b'] },
  { id: 90, name: 'Standard 500gm', businessType: ['b2c', 'b2b'] },
  { id: 91, name: 'Standard 2kg', businessType: ['b2c', 'b2b'] },
  { id: 92, name: 'Standard 5kg', businessType: ['b2c', 'b2b'] },
  { id: 93, name: 'Standard 10kg', businessType: ['b2c', 'b2b'] },
  { id: 94, name: 'Standard 20kg', businessType: ['b2c', 'b2b'] },
  { id: 95, name: 'Shadowfax Local', businessType: ['b2c', 'b2b'] },
  { id: 97, name: 'Dunzo Local', businessType: ['b2c', 'b2b'] },
  { id: 98, name: 'SRF Standard 5kg', businessType: ['b2c', 'b2b'] },
  { id: 99, name: 'Ecom Express ROS Reverse', businessType: ['b2c', 'b2b'] },
  { id: 100, name: 'Delhivery Surface 10 Kgs', businessType: ['b2c', 'b2b'] },
  { id: 101, name: 'Delhivery Surface 20 Kgs', businessType: ['b2c', 'b2b'] },
  { id: 106, name: 'Borzo', businessType: ['b2c', 'b2b'] },
  { id: 107, name: 'Borzo 5 Kg', businessType: ['b2c', 'b2b'] },
  { id: 114, name: 'SRF Standard 10kg', businessType: ['b2c', 'b2b'] },
  { id: 115, name: 'Shadowfax Savex', businessType: ['b2c', 'b2b'] },
  { id: 116, name: 'SRF Standard 20kg', businessType: ['b2c', 'b2b'] },
  { id: 117, name: 'SRF Express', businessType: ['b2c', 'b2b'] },
  { id: 118, name: 'Bluedart Savex Exchange', businessType: ['b2c', 'b2b'] },
  { id: 119, name: 'Identify Plus SDD Lite', businessType: ['b2c', 'b2b'] },
  { id: 120, name: 'Identify Plus SDD Standard', businessType: ['b2c', 'b2b'] },
  { id: 125, name: 'Xpressbees Reverse', businessType: ['b2c', 'b2b'] },
  { id: 126, name: 'Bluedart Savex TDD', businessType: ['b2c', 'b2b'] },
  { id: 130, name: 'Ekart 10kg', businessType: ['b2c', 'b2b'] },
  { id: 138, name: 'Delhivery Reverse 5kg', businessType: ['b2c', 'b2b'] },
  { id: 140, name: 'SRX Premium', businessType: ['b2c', 'b2b'] },
  { id: 141, name: 'SRF RUSH', businessType: ['b2c', 'b2b'] },
  { id: 142, name: 'Amazon Surface 500gm Prepaid', businessType: ['b2c', 'b2b'] },
  { id: 144, name: 'Xpressbees Reverse 2kg', businessType: ['b2c', 'b2b'] },
  { id: 145, name: 'Xpressbees Reverse 5 kg', businessType: ['b2c', 'b2b'] },
  { id: 146, name: 'Kerry Indev 2kg Surface', businessType: ['b2c', 'b2b'] },
  { id: 150, name: 'Xpressbees Reverse 1kg', businessType: ['b2c', 'b2b'] },
  { id: 154, name: 'Kerry Indev Express', businessType: ['b2c', 'b2b'] },
  { id: 159, name: 'Xpressbees 10kg', businessType: ['b2c', 'b2b'] },
  { id: 170, name: 'Ekart 2Kg', businessType: ['b2c', 'b2b'] },
  { id: 171, name: 'Ekart 5Kg', businessType: ['b2c', 'b2b'] },
  { id: 181, name: 'Amazon Shipping 10Kg', businessType: ['b2c', 'b2b'] },
  { id: 182, name: 'Amazon Shipping 20Kg', businessType: ['b2c', 'b2b'] },
  { id: 195, name: 'Amazon Surface 500gm COD', businessType: ['b2c', 'b2b'] },
  { id: 196, name: 'DTDC 500GMS', businessType: ['b2c', 'b2b'] },
  { id: 235, name: 'DTDC Express', businessType: ['b2c', 'b2b'] },
  { id: 240, name: 'SRX Priority', businessType: ['b2c', 'b2b'] },
  { id: 313, name: 'Wholemark', businessType: ['b2c', 'b2b'] },
  { id: 501, name: 'Bluedart CE Savex', businessType: ['b2c', 'b2b'] },
  { id: 524, name: 'Sm Shadowfax Surface 3Kg', businessType: ['b2c', 'b2b'] },
  { id: 777, name: 'Shadowfax DS', businessType: ['b2c', 'b2b'] },
]
